angular.module('solutionPrototype').factory('articlesService', function() {
  var articlesService = {
    getArticles: function() {
      return {
        "608300": {
          "title": "Wind + Solar Power Systems For Homes Or Businesses",
          "source": "cleantechnica.com",
          "intro": "Maine-based Pika Energy* makes some very interesting products. One of its most notable is the T701 residential wind turbine, which has a capacity of 1.5 kW. Another is the REbus microgrid, which can be used to combine its wind turbine with solar panels and connect them all to a home to make a complete, renewable energy system.",
          "url": "http://cleantechnica.com/2015/06/07/wind-solar-power-systems-homes-businesses/",
          "shared_by": ["gezgintrk"],
          "date": "10/26/2015",
          "share_count": {
            "facebook": 1077,
            "twitter": 119,
            "linkedin": 28
          }
        },
        "594924": {
          "title": "One of the world's largest solar parks set to power an Omani oil field",
          "source": "digitaltrends.com",
          "intro": "A solar-powered process called Enhanced Oil Recovery is about to power one of the world's largest solar parks at an oilfield in Oman, set to be fully functional by the end of 2017. The project will transform water into steam for injection into the Omani oilfield, powered by 1-gigawatt of completely renewable solar-thermal energy.",
          "url": "http://www.digitaltrends.com/business/worlds-largest-solar-farm-oil-oman-renewable-energy/",
          "shared_by": ["gezgintrk"],
          "date": "10/25/2015",
          "share_count": {
            "facebook": 88,
            "twitter": 298,
            "linkedin": 54
          }
        },
        "524072": {
          "title": "Wind now competes with fossil fuels. Solar almost does.",
          "source": "fortune.com",
          "intro": "Electricity generated by large wind farms is now cheap enough in many places around the world to compete effectively with electricity generated by coal and natural gas. At the same time, solar panel farms aren't quite low cost enough to be as competitive with fossil fuels as wind energy is.",
          "url": "http://fortune.com/2015/10/06/wind-cheap-coal-gas/",
          "shared_by": ["gustaf", "greenhousedata", "bloombergnef"],
          "date": "10/09/2015",
          "share_count": {
            "facebook": 3753,
            "twitter": 417,
            "linkedin": 123
          }
        },
        "523522": {
          "title": "castAR: the most versatile AR &amp; VR system",
          "source": "kickstarter.com",
          "intro": "Technical Illusions is raising funds for castAR: the most versatile AR &amp; VR system on Kickstarter! castAR: bridging the physical world with the virtual worlds; 3D holographic like projections in AR, fully immersive environments in VR",
          "url": "https://www.kickstarter.com/projects/technicalillusions/castar-the-most-versatile-ar-and-vr-system",
          "shared_by": ["nabeel"],
          "date": "10/08/2015",
          "share_count": {
            "facebook": 489,
            "twitter": 56,
            "linkedin": 217
          }
        },
        "511807": {
          "title": "Green Car Congress: Michigan State partners with ExxonMobil to advance algae biofuels",
          "source": "greencarcongress.com",
          "intro": "Print this post A new $1-million relationship between Michigan State University and ExxonMobil will expand research designed to progress the fundamental science required to advance algae-based fuels. David Kramer, MSU's John Hannah Distinguished Professor in Photosynthesis and Bioenergetics at the MSU-DOE Plant and Research Laboratory (PRL), says that the overall goal of the partnership is to improve the efficiency of photosynthesis in microalgae to produce biofuels and bioproducts.",
          "url": "http://www.greencarcongress.com/2015/10/20151001-msu.html?utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+greencarcongress%2FTrBK+%28Green+Car+Congress%29",
          "shared_by": ["gezgintrk"],
          "date": "10/02/2015",
          "share_count": {
            "facebook": 0,
            "twitter": 11,
            "linkedin": 1
          }
        },
        "431771": {
          "title": "How Does Solar Power Work? Does It Save Money?",
          "source": "latestsolarnews.com",
          "intro": "Solar energy is one of the best methods for providing almost unlimited amounts of energy for your home, and you may find that installing a solar panel system at home is the best way to reduce costs and protect the planet. But how does it work, and they...",
          "url": "http://latestsolarnews.com/how-does-solar-power-work-does-it-save-money/",
          "shared_by": ["gezgintrk"],
          "date": "09/14/2015",
          "share_count": {
            "facebook": 46,
            "twitter": 262,
            "linkedin": 8
          }
        },
        "414924": {
          "title": "Climate Study Predicts Huge Sea Level Rise if All Fossil Fuels Are Burned",
          "source": "nytimes.com",
          "intro": "Burning all the world's deposits of coal, oil and natural gas would raise the temperature enough to melt the entire ice sheet covering Antarctica, driving the level of the sea up by more than 160 feet, scientists reported Friday.",
          "url": "http://www.nytimes.com/2015/09/12/science/climate-study-predicts-huge-sea-level-rise-if-all-fossil-fuels-are-burned.html",
          "shared_by": ["bradplumer", "gustaf", "jcreaturetravel", "nytscience", "coralmdavenport"],
          "date": "09/11/2015",
          "share_count": {
            "facebook": 14660,
            "twitter": 1626,
            "linkedin": 206
          }
        },
        "247155": {
          "title": "This is why China is embracing clean energy: coal is killing people",
          "source": "fortune.com",
          "intro": "China spent a jaw-dropping $80 billion last year on clean energy, including wind projects and solar farms. That's more than double what the U.S. spent last year. One of the major reasons behind this spending spree is the country's serious air pollution problem, which is largely caused by dirty coal power plants.",
          "url": "http://fortune.com/2015/08/14/coal-is-killing-people/",
          "shared_by": ["gustaf", "JeunessePark"],
          "date": "08/14/2015",
          "share_count": {
            "facebook": 2489,
            "twitter": 356,
            "linkedin": 201
          }
        },
        "247265": {
          "title": "Fossil Fuel Generators Versus Green Energy",
          "source": "latestsolarnews.com",
          "intro": "Often we find the term 'green energy' or 'clean energy'. What does that mean exactly? In simple terms, this means that the source and method of energy that does not pollute the environment. The system is linked to the nature of the source and therefore, if...",
          "url": "http://latestsolarnews.com/fossil-fuel-generators-versus-green-energy/",
          "shared_by": ["gezgintrk"],
          "date": "08/14/2015",
          "share_count": {
            "facebook": 23,
            "twitter": 269,
            "linkedin": 6
          }
        },
        "204856": {
          "title": "How Cheap Can Solar Get? Very Cheap Indeed",
          "source": "rameznaam.com",
          "intro": "I'll attempt to make some projections (tentatively) here. tl;dr: If current rates of improvement hold, solar will be incredibly cheap by the time it's a substantial fraction of the world's electricity supply. It's now fairly common knowledge that the cost of solar modules is dropping exponentially.",
          "url": "http://rameznaam.com/2015/08/10/how-cheap-can-solar-get-very-cheap-indeed/",
          "shared_by": ["Noahpinion", "martinvars", "gustaf", "stephanierieger", "madisontaylormarketing4"],
          "date": "08/10/2015",
          "share_count": {
            "facebook": 2383,
            "twitter": 1194,
            "linkedin": 306
          }
        },
        "511816": {
          "title": "How to generate electricity from living plants",
          "source": "agenda.weforum.org",
          "intro": "Plant-e is one of the World Economic Forum's 2015 class of Technology Pioneers. How can you generate electricity from living plants? The company is developing technology that generates electricity from living plants without damaging them. Especially suitable for wet areas such as rice paddy fields, it could provide clean power to remote communities.",
          "url": "https://agenda.weforum.org/2015/08/how-can-you-generate-electricity-from-living-plants/",
          "shared_by": ["gezgintrk"],
          "date": "08/05/2015",
          "share_count": {
            "facebook": 2786,
            "twitter": 580,
            "linkedin": 869
          }
        },
        "148518": {
          "title": "Why SunEdison is buying Vivint Solar for $2.2 billion",
          "source": "fortune.com",
          "intro": "Clean energy company SunEdison announced on Monday morning that it plans to acquire Vivint Solar, which is one of the largest companies in the U.S. that installs solar panels on the rooftops of homes. SunEdison plans to pay $2.2 billion in the deal in a combination of cash and shares of SunEdison common stock and convertible notes.",
          "url": "http://fortune.com/2015/07/20/why-sunedison-is-buying-vivint-solar-for-2-2-billion/",
          "shared_by": ["gustaf"],
          "date": "07/20/2015",
          "share_count": {
            "facebook": 345,
            "twitter": 56,
            "linkedin": 227
          }
        },
        "133034": {
          "title": "Tesla CTO envisions a world where low cost batteries change everything",
          "source": "fortune.com",
          "intro": "Tesla's CTO JB Straubel predicts that low cost batteries will transform world transportation and access to electricity over the next decade. In a wide ranging talk at a solar conference in San Francisco on Monday night, Straubel painted a picture of a future society where all vehicles (other than planes and rockets) are one day powered by batteries, and new electricity systems are built with solar panels combined with batteries.",
          "url": "http://fortune.com/2015/07/14/tesla-cto-low-cost-batteries-change-everything/",
          "shared_by": ["gustaf"],
          "date": "07/14/2015",
          "share_count": {
            "facebook": 748,
            "twitter": 537,
            "linkedin": 180
          }
        },
        "199137": {
          "title": "Fossil fuels subsidised by $10m a minute, says IMF",
          "source": "theguardian.com",
          "intro": "Fossil fuel companies are benefitting from global subsidies of $5.3tn (£3.4tn) a year, equivalent to $10m a minute every day, according to a startling new estimate by the International Monetary Fund. The IMF calls the revelation 'shocking' and says the figure is an 'extremely robust' estimate of the true cost of fossil fuels.",
          "url": "http://www.theguardian.com/environment/2015/may/18/fossil-fuel-companies-getting-10m-a-minute-in-subsidies-says-imf",
          "shared_by": ["gustaf"],
          "date": "05/18/2015",
          "share_count": {
            "facebook": 105588,
            "twitter": 7175,
            "linkedin": 1757
          }
        },
        "511803": {
          "title": "Huge potential of grazing land for biofuel surge",
          "source": "scidev.net",
          "intro": "By Rodrigo de Oliveira Andrade [SAO PAULO] Converting grazing land into fields to grow crops for biofuels could provide up to 30 per cent of the world's energy needs, according to a report. The report says at least 500 million hectares are available for sustainable biofuel production even when rising food demand, growing urbanisation and the desire to preserve forest and protected lands are taken into account.",
          "url": "http://www.scidev.net/global/biofuels/news/biofuel-crops-boost-world-energy-matrix.html",
          "shared_by": ["gezgintrk"],
          "date": "01/10/2015",
          "share_count": {
            "facebook": 1146,
            "twitter": 103,
            "linkedin": 8
          }
        }
      }
    }
  }

  return articlesService;
})